name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - "eq2c-v*"

env:
  CARGO_TERM_COLOR: always
  BINARY_NAME: eq2c

jobs:
  build-and-release:
    name: Release - ${{ matrix.platform }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
            target: x86_64-unknown-linux-gnu
            asset_name: eq2c-linux-amd64
          - os: windows-latest
            platform: windows
            target: x86_64-pc-windows-msvc
            asset_name: eq2c-windows-amd64.exe

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: "${{ matrix.target }}"

      - name: Build Binary
        run: cargo build --release --target ${{ matrix.target }} --verbose

      - name: Prepare Asset
        shell: bash
        run: |
          if [ "${{ matrix.platform }}" == "windows" ]; then
            BIN_PATH="target/${{ matrix.target }}/release/${{ env.BINARY_NAME }}.exe"
          else
            BIN_PATH="target/${{ matrix.target }}/release/${{ env.BINARY_NAME }}"
          fi

          mv "$BIN_PATH" "${{ matrix.asset_name }}"

      - name: Create Release & Upload Assets
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          generate_release_notes: true
          files: |
            ${{ matrix.asset_name }}
